Upgrade to docker-machine. Prune boot2docker

diff --git a/docvm b/docvm
--- a/docvm
+++ b/docvm
@@ -10,7 +10,8 @@
 # TODO: Fix run and make it Generic
 
 SCRIPT_VERSION="2.6.5"
-CONFIG_PATH="./.docvm-config"
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+CONFIG_PATH=$DIR"/.docvm-config"
 
 
 function version {
@@ -22,8 +23,8 @@ function load_config {
 	print "Loading Config $CONFIG_PATH\n"
 	source $CONFIG_PATH || print "Fatal: Unable to Load Config!\n"
 
-	print "Config Variable BOOT2DOCKER_IP: 		$BOOT2DOCKER_IP \n"
-	print "Config Variable ETC_HOSTS_CONFIG: 	$ETC_HOSTS_CONFIG \n"
+	print "Found Variable DOCKER_MACHINE_IP: $DOCKER_MACHINE_IP \n"
+	print "Found Variable ETC_HOSTS_CONFIG:  $ETC_HOSTS_CONFIG \n"
 }
 
 
@@ -32,7 +33,7 @@ function bashinit {
 
 	echo "" >> $HOME/.bash_profile || exit 1
 	echo "# Initialize Boot2Docker Shell Commands" >> $HOME/.bash_profile || exit 1
-	echo "eval \$(boot2docker shellinit 2> /dev/null)" >> $HOME/.bash_profile && print "Done!\n"
+	echo eval "$(docker-machine env default) 2> /dev/null)" >> $HOME/.bash_profile && print "Done!\n"
 }
 
 
@@ -169,34 +170,6 @@ function gitclone {
 }
 
 
-function get_boot2docker {
-
-	if [ ! -f "/tmp/Boot2Docker-$B2DVERSION.pkg" ]
-	then
-		print "Downloading boot2docker-$B2DVERSION ... \n"
-		curl -L https://github.com/boot2docker/osx-installer/releases/download/v$B2DVERSION/Boot2Docker-$B2DVERSION.pkg -o /tmp/Boot2Docker-$B2DVERSION.pkg || exit 1
-		print "Done!\n"
-	else
-		print "Found: /tmp/Boot2Docker-$B2DVERSION.pkg\n"
-	fi
-}
-
-
-function install_boot2docker {
-	# Install boot2docker 1.6.2
-	b2d_version="$(boot2docker version 2> /dev/null)"
-
-	if [ ! -z "$b2d_version" ]
-	then
-		print "Found: 'boot2docker' installed\n"
-	else 
-		print "Installing boot2docker ... \n"
-		sudo installer -pkg /tmp/Boot2Docker-$B2DVERSION.pkg -target / || exit 1
-		print "Done!\n"
-	fi
-}
-
-
 function run_dockermachine {
 
 	dm_status=$(docker-machine status default 2> /dev/null) 
@@ -206,11 +179,9 @@ function run_dockermachine {
 		print "Found: 'docker-machine' running\n"
 	else
 		print "Initializing docker-machine ...\n"
-		# dockermachine init || exit 1
-		# dockermachine up || exit 1
-		# eval "$(docker-machine shellinit)" || exit 1
-		# print "Done!\n"
-		print "Error! Not Implemented\n"
+		docker-machine start default || exit 1
+		eval "$(docker-machine env default)" || exit 1
+		print "Done!\n"
 	fi
 
 }
@@ -232,13 +203,14 @@ function init_docker {
 
 }
 
+# Deprecated
 function init_boot2docker {
 	
 	get_boot2docker	
 
 	install_boot2docker	
 
-	run_dockermachine
+	run_boot2docker
 
 	return 1
 }
@@ -247,13 +219,13 @@ function init_boot2docker {
 function init_dockermachine {
 
 	# get_dockermachine
-
 	# install_dockermachine
 
 	run_dockermachine
 
 	return 1
 }
+
 
 function is_running {
 	echo $(docker ps | grep $DOCKER_IMAGE | wc -l)
@@ -324,6 +296,7 @@ function shell {
 }
 
 
+
 function uninstall_boot2docker {
 	# uninstalls Boot2Docker (not virtual box, or directory cleanup)
 	boot2docker delete &> /dev/null
@@ -388,12 +361,12 @@ function init {
 
 
 function shellinit-volatile {
-	if hash boot2docker 2>/dev/null
+	if hash docker-machine 2>/dev/null
 	then
-		eval $(boot2docker shellinit 2>/dev/null) || \
-		print "WARN: 'boot2docker' shellinit Failed! \n"
+		eval "$(docker-machine env default) 2>/dev/null)" || \
+		print "WARN: 'docker-machine' environ init Failed! \n"
 	else
-		print "INFO: 'boot2docker' Not Found! \n"
+		print "INFO: 'docker-machine' Not Found! \n"
 	fi
 	# TODO: Send Feedback Message to User
 }
